### PR TITLE
Rename cloud package to types

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```release-note
none
```

/assign @mrIncompetent

### CODE REVIEW

**Comment by alvaroaleman** [comment]
> Mostly ok with intention. Only one question about cloudprovider/interface/provider.go. Still package cloud in there?

Good point, that was missing. And turns out calling a package `interface` causes issues. I have instead renamed it to `types`, which also fits a little bit better, as the package does not only contain interfaces.

**Comment by alvaroaleman** [comment]
@themue PTAL

**Comment by nikhita** [comment]
@alvaroaleman you'll need to approve yourself :)

**Pull request merged**
