### PR TITLE
Fix failing download script on flatcar due to read-only filesystem

### PR DESCRIPTION
**Pull request by FlorinPeter**
**What this PR does / why we need it**:
This PR fixes the following error on flatcar
```
Oct 05 06:00:24 c19-worker-infra-0-b66bf5f8f-5r9nd download.sh[965]: + rm -f crictl-v1.22.0-linux-amd64.tar.gz
Oct 05 06:00:24 c19-worker-infra-0-b66bf5f8f-5r9nd download.sh[965]: + ln -sf /opt/bin/crictl /usr/local/bin/crictl
Oct 05 06:00:24 c19-worker-infra-0-b66bf5f8f-5r9nd download.sh[1226]: ln: failed to create symbolic link '/usr/local/bin/crictl': Read-only file system
```

**Special notes for your reviewer**:
This patch was tested with Flatcar 2905.2.3 (Oklo)

**Optional Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FlorinPeter** [comment]
@kron4eg I rebased again can you remove the hold?

**Review by kron4eg — APPROVED** [review]
/hold cancel

**Pull request merged**
