### PR TITLE
[release/v1.54] Anexia Provider: add support for named VM templates

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:

This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1541

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: Optionally configure "named templates" instead of (less stable) "template identifiers".
```

**Documentation**:

```documentation
https://github.com/kubermatic/machine-controller/blob/main/docs/anexia.md
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by LittleFox94** [comment]
@ahmedwaleedmalik could we have a 1.54 release including this and the other recent changes? :)

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik could we have a 1.54 release including this and the other recent changes? :)

Releases are out now:
- https://github.com/kubermatic/machine-controller/releases/tag/v1.56.1
- https://github.com/kubermatic/machine-controller/releases/tag/v1.54.6

**Pull request merged**
