### PR TITLE
Add template files and boilerplate headers

### PR DESCRIPTION
**Pull request by nikhita**
For making sure it complies according to our open source standards. 

**Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
/retest

/lgtm
/approve

/hold

@alvaroaleman Any objections?

**Comment by mrIncompetent** [comment]
The hetzner apt mirrors seem to have problems:
```
E: Failed to fetch http://mirror.hetzner.de/ubuntu/packages/dists/bionic/main/binary-amd64/Packages  404  Not Found [IP: 213.133.99.97 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
+ sleep 1s
```

Lets wait a few hours and retry

**Comment by nikhita** [comment]
Trying again :crossed_fingers: 

/retest

**Pull request merged**
