### PR TITLE
Support for Kubernetes 1.30

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
This PR covers the following:
- Support for Kubernetes 1.30
- Use the latest available patch releases in E2E tests i.e. 1.29.4, 1.28.9, 1.27.13
- Update the Kubernetes version to `1.29.4` in our [examples](https://github.com/kubermatic/machine-controller/tree/main/examples)
- Due to a [breaking change](https://github.com/kubernetes/kubernetes/pull/122069)  in `k8s.io/client-go/tools/leaderelection` in v0.30.0, we are pinning controller-runtime to https://github.com/kubernetes-sigs/controller-runtime/commit/04706074d2f13af5d21731c24b9a1d7ed8197f38 for now. This needs to be updated once a new version with https://github.com/kubernetes-sigs/controller-runtime/pull/2693 included is released. Since we are not expecting a new minor release anytime soon it's fine to pin this for now. 

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
machine-controller now supports Kubernetes v1.30 
```

**Documentation**:

```documentation
TBD
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
> pull-machine-controller-e2e-kubevirt

`Get "https://kubeapi.kubevirt-1.dc.k8c.io:6443/apis/kubevirt.io/v1": net/http: TLS handshake timeout`

**Comment by ahmedwaleedmalik** [comment]
> pull-machine-controller-e2e-vsphere

We have lost the host where the VM template for `kkp-rockylinux-8` was hosted, so this will fail for the time being.

**Review by kron4eg — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
