### PR TITLE
Feature/add vendors to repo

### PR DESCRIPTION
**Pull request by guusvw**
**What this PR does / why we need it**:

Add vendors to the repository
* removed vendors from `.gitignore`
* update `Gopkg.lock`
* add vendors

**Special notes for your reviewer**:

Next steps:

* update build process to use also vendors

### CODE REVIEW

**Comment by alvaroaleman** [comment]
IMHO after a rebase this is good to go or what do you think @mrIncompetent ?

**Comment by mrIncompetent** [comment]
Circle CI update is missing, or?

**Comment by alvaroaleman** [comment]
Oh you are right there

**Comment by mrIncompetent** [comment]
@guusvw any update?

**Comment by alvaroaleman** [comment]
@guusvw Can you configure the `Gopkg.toml` like this so we only vendor code and licenses but not docs and whatnot:

```
[prune]
  non-go = true
  go-tests = true
  unused-packages = true
```

**Pull request closed without merging**
