### PR TITLE
Update to golang 1.18.1 and corresponding kubermatic/build image

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

Bit of housekeeping: Bumps Go to 1.18.1 since the in-use version could use an update.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
Go version has been updated to 1.18.1
```

Signed-off-by: Marvin Beckers <marvin@kubermatic.com>

### CODE REVIEW

**Comment by embik** [comment]
/hold

I don't want this to go into `master` before #1267

**Review by ahmedwaleedmalik — COMMENTED** [review]
Please update https://github.com/kubermatic/machine-controller/blob/master/go.mod#L3 to 1.18 ;)

**Comment by embik** [comment]
> Please update https://github.com/kubermatic/machine-controller/blob/master/go.mod#L3 to 1.18 ;)

We didn't do that for KKP either when updating to Go 1.18, see https://github.com/kubermatic/kubermatic/blob/50401e3028a85f63035a4388057a86536870c8f6/go.mod. Not sure we need to do that, 1.17 should continue to work fine as long as we don't start using new language features.

**Comment by ahmedwaleedmalik** [comment]
Please run `go mod tidy` once and then it'd be good to go.

**Pull request merged**
