### PR TITLE
Fix empty network config handling

### PR DESCRIPTION
**Pull request by eiabea**
**What this PR does / why we need it**:
Provisioning a VM without defining a `Network` in the `providerConfig` object results in a nil pointer exception. This bug got introduced by https://github.com/kubermatic/machine-controller/pull/1637

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

We'd love to get a backport of these changes in v1.54

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: Fix nil pointer exception when providing no network configuration
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by LittleFox94** [comment]
This is a bug introduced in #1637, right? If so, should be mentioned in the description

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
@eiabea please fix the unit tests

**Review by ahmedwaleedmalik — APPROVED** [review]
/ok-to-test

**Comment by ahmedwaleedmalik** [comment]
@eiabea you'll have to manually cherry pick this to `release/v1.56` and `release/v1.54`

**Pull request merged**
