### PR TITLE
Support Nautobot client in machine controller

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Support Nautobot minimal client which will be used to provision baremetal clusters
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The client is not being used in the baremetal provider. will be added once tested in a separate commit 
**Optional Release Note**:

```release-note
Nautobot client support
```

### CODE REVIEW

**Comment by mfranczy** [comment]
In my opinion, the entire nautobot client should be in a different repository and used in the machine controller.

**Comment by moadqassem** [comment]
> In my opinion, the entire nautobot client should be in a different repository and used in the machine controller.

Well, this is what I have mentioned earlier, that this client shouldn't be part of the machine-controller because it can be bounded directly to specific DC setup. For now, there is no other place that suits this client however in the future we can find another place or even a service that should contain this client

**Comment by mfranczy** [comment]
> For now, there is no other place that suits this client however in the future we can find another place or even a service that should contain this client

I meant a dedicated repositroy only for nautobot client

**Comment by mfranczy** [comment]
I still think that should be a separate client, although others thing in a different way, evenutally we might move this client once we have other consuments.

/lgtm

**Pull request merged**
