### PR TITLE
Support for Hetzner arm64 architecture instances

### PR DESCRIPTION
**Pull request by 7oku**
**What this PR does / why we need it**:
Hetzner provides CAX instances with arm64 architecture. An appropriate image has to be given to the hcloud module, which is suitable for arm64 instances. 

The PR implements additional mechanisms to determine the new `hcloud.ServerType.Architecture` field and use the hcloud modules new method `Image.GetForArchitecture()` to determine the correct image for arm64 ServerTypes and allows machine-controller to successful deploy CAX instances.

**Which issue(s) this PR fixes**:
Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:
I had to test the change with the latest release of MC (v1.59.2) as my test environment uses kubeone 1.8. The latest changes to MC break the kubernetes deployment, as a lot of flags (use-osm etc.) have been removed in `main` recently. Since I did not touch anything else other than the hetzner provider and `make test-unit` succeeded, it should work fine in upcoming releases. But feel free to test prior accepting the PR.

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Support for Hetzner arm64 architecture instances
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
Looking good, thank you for the contribution! Let's see if it passes e2e tests.

/ok-to-test

**Comment by 7oku** [comment]
@embik #1818 was prioritized in the meantime and changed base for my pr fundamentally. had to do some rework. retesting was successful, so it's ready to be merged again from my side now.

**Comment by P4sca1** [comment]
Sorry for causing the merge conflicts. Your change looks good to me and is a useful addition!

**Comment by embik** [comment]
Hey, thanks for updating the PR after the merge conflict. I'm currently checking if we have any concerns with the upgrade to the hcloud-go/v2 version, I'll make sure to get back to you ASAP!

**Comment by 7oku** [comment]
Hey @embik no problem, we could potentially roll back to hcloud-go/v1 (1.56.0 or so), but according to https://github.com/hetznercloud/hcloud-go/issues/263#issuecomment-1632562098 v1 is deprecated since Sep 2023. Upgrading only took the effort to convert int to int64, so not a big deal.

Other than here in the Hetzner provider I did not find any other occurrence of hcloud module in machine-controller.

@P4sca1 all good, I'm happy to see development on the Hetzner provider.

**Review by embik — APPROVED** [review]
/approve

Thank you for the contribution, it is greatly appreciated! 🎉

**Pull request merged**
