### PR TITLE
[release/v1.54] Anexia Provider: Fix empty network config handling

### PR DESCRIPTION
**Pull request by eiabea**
**What this PR does / why we need it**:
Backport for #1646

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: Fix nil pointer exception when providing no network configuration
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by eiabea** [comment]
Are the failing tests caused by the e2e infrastructure? Because i can not find any code related issues

**Comment by ahmedwaleedmalik** [comment]
> Are the failing tests caused by the e2e infrastructure? Because i can not find any code related issues

The failing tests are on us. I'm assuming someone would fix them before the new release and then we can move forward with this PR as well. So nothing is required from your side. :D

**Review by ahmedwaleedmalik — APPROVED** [review]
/unhold

**Pull request merged**
