### PR TITLE
[release/v1.57] Configure provider-id for the machines/nodes 

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Manual backport of #1723 

**Which issue(s) this PR fixes**:

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Machine-controller will inject provider-id for the machines that are created against cloud providers that don't have in-tree or external CCM support
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
:mage: Approving in absence of any SIG Virt members.

**Comment by ahmedwaleedmalik** [comment]
@xrstf you'll have to override the `pull-machine-controller-e2e-vsphere` as well, seems like vCenter is having issues.

**Pull request merged**
