### PR TITLE
KubeVirt cleanup small wrong code (preference error check)

### PR DESCRIPTION
**Pull request by hdurand0710**
Signed-off-by: Helene Durand <helene@kubermatic.com>

**What this PR does / why we need it**:
This PR cleans up a small wrong code. Behaviour does not change but this lines should go.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by hdurand0710** [comment]
For AWs, tests are failing with 
E1115 08:59:37.676286       1 machine_controller.go:382] Failed to reconcile machine "centos-1-23-13-aws-1592439865218174976-6df6478964-rzh58": An error of type = InvalidConfiguration, with message = Failed to get AMI-ID for operating system centos in region eu-central-1: could not find Image for 'centos' with arch 'x86_64' occurred

**Pull request merged**
