### PR TITLE
Fix typo in the GlobalObjectKeySelector type name

### PR DESCRIPTION
**Pull request by nikhita**
Generates swagger.json with the typo in kubermatic :P 

/assign @alvaroaleman 

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
>         helper.go:151: verify failed due to error=failed to verify creation of node for MachineDeployment: Internal error occurred: admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: defaulting or validation failed: validation failed: failed to request VirtualMachineInstances: no matches for kind "VirtualMachineInstance" in version "kubevirt.io/v1alpha2"

@moadqassem this error occurred twice, looks like a legit one? :thinking:

**Comment by alvaroaleman** [comment]
/override pull-machine-controller-e2e-kubevirt

It needs Moadhs PR to work, sorry for the inconvenience

**Comment by moadqassem** [comment]
@nikhita It's because of the version of the VMI object, the current version that we run in the e2e test cluster is `v1lpha3` and the one that you are trying to get is v1alpha2, but once this #339 is merged it will be solved

**Pull request merged**
