### PR TITLE
Anexia: extend network configuration to allow multi-interface and multi-IP

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

Can now create multiple network interfaces, each with multiple addresses (one from each configured prefix), easily allowing Machines to have e.g. an IPv4 and IPv6 address.

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

We had an internal review already, which you see in the PR of our fork: https://github.com/anexia-it/machine-controller/pull/23

Might add some context if something looks odd.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia: extend network configuration, allowing multiple interfaces and multiple IPs per interface
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
Some files are missing the boilerplate

**Comment by LittleFox94** [comment]
> Some files are missing the boilerplate

oops, gonna fix - sorry!

**Comment by LittleFox94** [comment]
@ahmedwaleedmalik the failed GCE tests look very unrelated, can we ignore them?

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
