### PR TITLE
Add label on machine to differentiate between the tool used for managing machine configurations

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Add label on machine to differentiate between the tool used for managing machine configurations.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
What's the plan on how to use this label?

**Comment by ahmedwaleedmalik** [comment]
I want a metric to differentiate between the machines created using OSM and those without them. This can be used for migration to OSM. Maybe we can even show this at the front-end. It'd be a warning in the view for machine or machine deployment that this machine is using legacy user data.

**Pull request merged**
