### PR TITLE
Move module to k8c.io/machine-controller

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Move the machine-controller module from `github.com/kubermatic/machine-controller` to `k8c.io/machine-controller`. We have done this a long time ago for other projects, but machine-controller had some technical blockers. Those blockers got resolved along the way, and now we can finally proceed with this change.

**What type of PR is this?**

/kind feature
/kind api-change

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
[ACTION REQUIRED] Move the machine-controller Go module from `github.com/kubermatic/machine-controller` to `k8c.io/machine-controller`. If you're using machine-controller types or packages, you'll have to update your code to use `k8c.io/machine-controller`.
```

**Documentation**:
```documentation
NONE
```

/assign @xrstf 
/hold requires infra changes

### CODE REVIEW

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-azure no RHEL sub anymore
/override pull-machine-controller-e2e-vmware-cloud-director capacity issues

**Comment by xmudrii** [comment]
/hold cancel
:shipit:

**Pull request merged**
