### PR TITLE
Disable flatcar tests for vsphere

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Disable flatcar tests for vSphere temporarily until the image is available 
**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
None
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

**Review by embik — APPROVED** [review]

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
