### PR TITLE
Enable --resolv-conf=/run/systemd/resolve/resolv.conf kubelet flag for Flatcar

### LINKED ISSUE #1377: CoreDNS crash loop on Flatcar 3227.2.0
As of Flatcar 3227.2.0 (which was released as an AMI on Jul 19 2022), CoreDNS gets stuck in a crash loop due to the underlying /etc/resolv.conf on nodes.

`[FATAL] plugin/loop: Loop (127.0.0.1:41860 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 6678297518826138904.7682940538006338517."`

This is due to the /etc/resolv.conf of the host being a symlink that points at /run/systemd/resolve/stub-resolv.conf which contains a nameserver entry for 127.0.0.53. Before Flatcar 3227.2.0, it was a symlink that pointed to /run/systemd/resolve/resolv.conf, which contains a nameserver entry with an IP local to this node's network.

I believe a fix is needed similar to what you're already doing for a couple OSs, like Ubuntu - https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/ubuntu/provider.go#L271 - where you override the default resolv.conf for kubelet and point it at the other location.

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
To prevent DNS loops of CoreDNS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #1377

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
Enable --resolv-conf=/run/systemd/resolve/resolv.conf kubelet flag for Flatcar
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by kron4eg** [comment]
> @[kron4eg](https://github.com/kron4eg) [force-pushed](https://github.com/kubermatic/machine-controller/compare/d4c88daab2c0e61ae9c851267ec23de523267e9f..80f7e841960d6a38a30f167d0c910d042a2be06e) the systemd-resolved branch from[ d4c88da ](https://github.com/kubermatic/machine-controller/commit/d4c88daab2c0e61ae9c851267ec23de523267e9f)to[ 80f7e84 ](https://github.com/kubermatic/machine-controller/commit/80f7e841960d6a38a30f167d0c910d042a2be06e)

I've dropped changes for amzn2 and centos, since they don't have systemd-resolved service.

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-hetzner

Hetzner is down.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve ⚡

**Pull request merged**
