### PR TITLE
adjust rhel bootstrapping script

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Bootstrapping script for rhel.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
None
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/lgtm
/approve

**Comment by toschneck** [comment]
@moadqassem  can we please add, what have been fixed? Somehow it would help us if we run at issues to find out what have been already fixed. Thanks in advance for sharing

**Comment by moadqassem** [comment]
> @moadqassem can we please add, what have been fixed? Somehow it would help us if we run at issues to find out what have been already fixed. Thanks in advance for sharing

@toschneck This is OSM related.

**Pull request merged**
