### PR TITLE
Update OSM deployment for E2E tests

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Update deployment for OSM, used in E2E tests.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-vsphere

vSphere/VPN is broken yet again.

**Comment by ahmedwaleedmalik** [comment]
> pull-machine-controller-e2e-azure
```
W1130 09:43:12.662123   29905 verify.go:157] Creation of "centos-1-25-3-azure-1597882853960454144" failed, retrying: admission webhook "machinedeployments.machine-controller.kubermatic.io" denied the request: validation failed: failed to list virtual machines: compute.VirtualMachinesClient#List: Failure sending request: StatusCode=429 -- Original Error: context canceled
```

/test pull-machine-controller-e2e-azure

**Pull request merged**
