### PR TITLE
rename master branch to main

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
We are in the process of renaming the master branch across all repos, and this PR prepares this repo for the renaming.

/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
The primary Git branch was renamed from `master` to `main`.
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-aws
/override pull-machine-controller-e2e-aws-arm
/override pull-machine-controller-e2e-aws-ebs-encryption-enabled
/override pull-machine-controller-e2e-aws-flatcar-containerd
/override pull-machine-controller-e2e-aws-legacy-userdata
/override pull-machine-controller-e2e-aws-spot-instance
/override pull-machine-controller-e2e-azure
/override pull-machine-controller-e2e-azure-custom-image-reference
/override pull-machine-controller-e2e-deployment-upgrade
/override pull-machine-controller-e2e-digitalocean
/override pull-machine-controller-e2e-hetzner
/override pull-machine-controller-e2e-openstack
/override pull-machine-controller-e2e-openstack-project-auth
/override pull-machine-controller-e2e-ubuntu-upgrade

**Pull request merged**
