### PR TITLE
Change vcenter datastore to ceph

### PR DESCRIPTION
**Pull request by WeirdMachine**
**What this PR does / why we need it**:

Changes vcenter datastore to ceph

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/retest

**Comment by WeirdMachine** [comment]
/close 

in favor of https://github.com/kubermatic/machine-controller/pull/1482

**Pull request closed without merging**
