### PR TITLE
[release/v1.54] Anexia Provider: Utilize `Creating` state instead of blocking `Create…

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

Manual cherry-pick of #1483 

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia: Refactor code to reduce provisioning time for node pools with multiple replicas.
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by LittleFox94** [comment]
Since @ahmedwaleedmalik reviewed the original PR, it would probably make sense if you take a look at this one as well - thanks :)

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by LittleFox94** [comment]
this should probably also go into `release/v1.55`, what do you think?

**Comment by ahmedwaleedmalik** [comment]
> this should probably also go into `release/v1.55`, what do you think?

In general 1.55 is only used in KubeOne at the moment. I have added the backport though.

**Comment by LittleFox94** [comment]
> > this should probably also go into `release/v1.55`, what do you think?
> 
> In general 1.55 is only used in KubeOne at the moment. I have added the backport though.

just thought it might be weird to have a change in main and a release older than the latest one, but not in the latest release - thanks :)

**Comment by LittleFox94** [comment]
Hi @ahmedwaleedmalik,
since we still use KKP 2.20, we'd need this backported to v1.45 as well - could you cherry-pick this or should we create the PR manually?

**Comment by ahmedwaleedmalik** [comment]
> Hi @ahmedwaleedmalik, since we still use KKP 2.20, we'd need this backported to v1.45 as well - could you cherry-pick this or should we create the PR manually?

I'll take care of that.

**Pull request merged**
