### PR TITLE
Update cri-tools to v1.26.0

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Update `cri-tools` to v1.26.0. This is required for the latest (January 2023) Kubernetes patch releases. This PR also includes an update to the checksum checking for cri-tools: https://github.com/kubermatic/operating-system-manager/pull/258

Reference: https://github.com/kubernetes/release/pull/2821

**What type of PR is this?**
/kind feature

**Does this PR introduce a user-facing change? Then add your Release Note here**:
```release-note
Update cri-tools to v1.26.0
```

**Documentation**:
```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve 🚀

**Comment by xmudrii** [comment]
v1.26 tests for OpenStack are broken (irrelevant to this PR). Kubevirt tests are to be investigated.
/hold

**Pull request merged**
