### PR TITLE
Refactoring of KubeVirt PVC image source

### PR DESCRIPTION
**Pull request by mfranczy**
**What this PR does / why we need it**:
Remove env vars that control PVC source.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Remove KubeVirt image PVC source control from env vars
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by mfranczy** [comment]
/hold

didn't test yet, however @hdurand0710 it's good for a review

**Comment by hdurand0710** [comment]
/approve
I like it, I let you test, but looks good!

**Pull request merged**
