### PR TITLE
Enable more golangci-linters 

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Enable more golangci-linters. The list of linters has been taken from https://github.com/kubermatic/kubermatic/blob/master/.golangci.yml#L33

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
`gocritic` has been left out on purpose since that is a bit complex. I'll take care of that in a follow-up, dedicated PR.

**Optional Release Note**:

```release-note
Metric `machine_controller_machines` was renamed to `machine_controller_machines_total`.
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
`pull-machine-controller-e2e-nutanix` should be overridden since Nutanix is dead at the moment.

**Comment by ahmedwaleedmalik** [comment]
Nice, so migrate UID tests are failing because of my shenanigans.

**Review by xrstf — APPROVED** [review]
Love it! ❤️ 

/approve

**Comment by ahmedwaleedmalik** [comment]
> hcloud_network.net: Creating...
Error: network limit reached (resource_limit_exceeded)

Ah, here we go again.

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-nutanix

As requested by @ahmedwaleedmalik

**Review by PratikDeoghare — APPROVED** [review]

**Pull request merged**
