### PR TITLE
[release/v1.54] Anexia Provider: configure rpc-statd service as kubelet dependency

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
This is a manual cherry-pick of https://github.com/kubermatic/machine-controller/pull/1553

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Enables "rpc-statd" service on new Anexia Machines using Flatcar with cloud-init to enable NFS functionality required by Anexia CSI driver.
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by xrstf** [comment]
Please adjust the release branch, these are not flakes.

/override pull-machine-controller-e2e-kubevirt
/override pull-machine-controller-e2e-vmware-cloud-director
/override pull-machine-controller-e2e-vsphere

**Comment by marioreggiori** [comment]
> Please adjust the release branch, these are not flakes.

@xrstf I assume those errors are unrelated to this PR and this message wasn't directed to me?

**Comment by ahmedwaleedmalik** [comment]
> > Please adjust the release branch, these are not flakes.
> 
> @xrstf I assume those errors are unrelated to this PR and this message wasn't directed to me?

This message was for me and our dev team :D Not directed to you folks.

**Pull request merged**
