### PR TITLE
Refactor Ubuntu ARM image in AWS 

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Update ubuntu 24.04 arm image in aws
**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
None
```

**Documentation**:

```documentation
None
```

### CODE REVIEW

**Comment by moadqassem** [comment]
/hod would like to do one last test

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

@moadqassem can you please add a release note if this is a bug? Also, do we need to backport this?

**Comment by ahmedwaleedmalik** [comment]
Umm what, I thought it was on hold

> /hod would like to do one last test

So a typo there, we can use a follow-up PR if required

**Comment by moadqassem** [comment]
> Umm what, I thought it was on hold
> 
> > /hod would like to do one last test
> 
> So a typo there, we can use a follow-up PR if required

All good :D I mean it should work as I tested it briefly but I had issues with my testing cluster(cni ;) ) I will bump machine controller in KKP main and KKP 2.26 now.

**Pull request merged**
