### PR TITLE
windows support

### LINKED ISSUE #904: Add support for Windows Worker Nodes
Please add support for windows worker nodes, so that windows based workload can be added to the cluster.

From what I've seen so far, the only hard pre-requirement for this is that either the cloud provider installed cloud base cloud-init within the image or that the user can upload such an image.

The cloud-init script would have to take care of:
1. Install [OpenSSH](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
2. Install latest (stable) PowerShell Core (optional)
3. Activate Windows using a valid license (optional, there are ways the service provider could take care of this automatically, e.g. [AVMA](https://docs.microsoft.com/de-de/windows-server/get-started-19/vm-activation-19), [KMS/MAK](https://docs.microsoft.com/de-de/windows-server/get-started-19/activation-19))
4. Configure networking.
5. Install latest system updates.
6. Go through this steps to join the worker node: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#joining-a-windows-worker-node

Related resources:
* [Support Matrix](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#supported-functionality-and-limitations)
* [Guide for scheduling Windows containers](https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/)

### PR DESCRIPTION
**Pull request by agowa338**
**What this PR does / why we need it**: Adding support for windows images

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #904

**Special notes for your reviewer**:
There are currently a few parts that are marked "TODO" as I'm not quite sure how to address these. I'm going to look into them again, but I'd appreciate some help there.

- [ ] `docs/operating-system.md`: List of cloud providers that support/provide windows images.
- [ ] `pkg/containerruntime/containerruntime.go`: Does the change to the Engine interface break others?
- [ ] `pkg/containerruntime/docker.go`: Installing docker on windows requires a restart before the service can be started. ~I don't know how to implement that.~
- [ ] ContainerRuntimeConfig: Currently only the default configuration is written. The templating function is unused. I got a bit confused there with all the options.
- [ ] `pkg/userdata/windows/provider_test.go`: Currently just a renamed copy of another distros test. Aka. still needs to be implemented (as does the test data)
- [x] I don't know how to build and run machine-controller locally right now. Therefore this code is completely untested.
- [ ] currently I only wrote about acquiring the windows images from Microsoft directly (registration required and no perma links). Maybe we could use vagrant, but Microsoft itself only published a Windows 10 with edge version a few years ago and pulling images from "some random 3rd party" may not be the best decision (regarding security and legal aspects). https://app.vagrantup.com/Microsoft
- [x] kubelet connects to control plane
- [x] network cni is working
- [x] hostname is set correctly
- [x] hostname is registered correctly
- [x] containerd runtime working
- [x] (containerd) node is fully online and operational (e.g. can start a pod)
- [ ] docker runtime working
- [ ] (docker) node is fully online and operational (e.g. can start a pod)
- [ ] Hyper-V "isolation" (aka. Microsoft labeling VMs as container) support
- [ ] testing the scripts for finding timing and environmentally dependent issues
- [ ] optimizing the scripts
- [ ] Implement ARM64 support

**Optional Release Note**:

```release-note
Added support for Windows Nodes.
```

### CODE REVIEW

**Comment by ewassef** [comment]
How can I help!?? We NEED this too

**Comment by agowa338** [comment]
Hi @ewassef I keep track of the open doings in the entry post.
For now the most important points are:
* Testing: I only have limited systems to run this against and the cloud-init scripts still have many timing issues (and issues related to what the cloud provider put into the cloud init configuration file)
* Docker support: I not tested if it works with docker (it most likely will fail at some point within the script)
* The network cni: Currently I have no clue how the networking works with windows nodes.
* Writing the unit test: I don't know (until now) how exactly golang unit tests work.
* Optimize the scripts: As you can see the scripts are very WIP and not optimized for performance.
* Hyper-V support: My openstack cloud provider doesn't support nested virtualization so I cannot test that.

**Comment by ewassef** [comment]
@agowa338  Thanks for the update. I will see what we can do and reach out.

**Comment by agowa338** [comment]
containerd is now completely working. I'm able to install flannel and deploy pods.

For installing flannel this is required: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

On the control plane (based upon the one generated by this project)
1. `wget https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`
2. Modify net-conf.json as described in the above link
3. `kubectl apply -f kube-flannel.yml`
4. `curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/VERSION/v1.20.0/g' | kubectl apply -f -`
5. `kubectl apply -f https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml`
6. Wait for flannel to be deployed: `kubectl get nodes -o wide`

**Comment by shaase-ctrl** [comment]
@moadqassem What do we need to do here?

**Pull request closed without merging**
