### PR TITLE
Simplify the vCenter client creation

### PR DESCRIPTION
**Pull request by mrIncompetent**
```release-note
NONE
```

/assign @alvaroaleman

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/lgtm
/approve
Modulo the vsphere job so
/hold

**Comment by mrIncompetent** [comment]
/retest

Seems the test is flakey, i ran the controller locally and everything works

**Comment by mrIncompetent** [comment]
@alvaroaleman test succeeded :)

**Comment by mrIncompetent** [comment]
@alvaroaleman 
i'm a grown up. I can remove the hold on my own.

/hold cancel

**Pull request merged**
