### PR TITLE
Add spot instance flag to example doc

### PR DESCRIPTION
**Pull request by toschneck**
And missing boolean flag of https://github.com/kubermatic/machine-controller/blob/master/pkg/cloudprovider/provider/aws/types/types.go#L33

**What this PR does / why we need it**:
Example is missing this feature

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Test the provisioning, machine get created:
image

**Optional Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by irozzo-1A** [comment]
@toschneck This document should be updated too [AWS cloud provider doc](https://github.com/kubermatic/machine-controller/blob/master/docs/cloud-provider.md#aws) I think.

**Comment by kdomanski** [comment]
@toschneck ping

**Comment by toschneck** [comment]
@irozzo-1A @kdomanski done, wasn't aware about this doc :)

**Pull request merged**
