### PR TITLE
Migrate AWS cloud provider to AWS Go SDK v2

### LINKED ISSUE #1417: Migrate to AWS SDK for Go v2
We're currently using the AWS SDK for Go in v1. The [v2 SDK](https://aws.github.io/aws-sdk-go-v2/docs/) has some neat stuff like being able to re-use our contexts that we currently discard on the AWS provider.

We should migrate to v2 to make sure we're staying up to date with AWS APIs and pull in potential stability improvements in communicating with the AWS APIs.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:
This migrates the `aws` cloud provider for machine-controller to the v2 of AWS' official Go SDK.

I saw random OOM kills on Prow jobs for this PR, so I'm bumping the memory to 7Gi to make sure this doesn't happen to others. I assume compiling the v2 SDK needs more memory or something like that.

**Which issue(s) this PR fixes**:

Fixes #1417

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
The AWS cloud provider implementation now uses the AWS Go SDK v2 to communicate with AWS
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

**Comment by embik** [comment]
/hold

So failing tests don't re-run.

**Pull request merged**
