### PR TITLE
Anexia Provider: fix cleanup of failed machines

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
This PR makes it possible to `Cleanup` Machines which have no instance (because they failed creation e.g. due to invalid configuration).

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: fix cleanup of failed machines
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve 🚀

**Comment by marioreggiori** [comment]
I think https://github.com/kubermatic/machine-controller/pull/1571 needs to be backported to the `release/v1.56` branch as well

**Pull request merged**
