### PR TITLE
Adding kubevirt dnsconfig

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Support `DNSConfig` propagation from the `MachineDeployment` to the Kubevirt `VM`.
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

```release-note
None
```

### CODE REVIEW

**Comment by xrstf** [comment]
Overriding because our local vSphere is down:

/override pull-machine-controller-e2e-vsphere
/override pull-machine-controller-e2e-vsphere-resource-pool

**Comment by xrstf** [comment]
Overriding because our local vSphere is down:

/override pull-machine-controller-e2e-vsphere
/override pull-machine-controller-e2e-vsphere-resource-pool

**Comment by toschneck** [comment]
@moadqassem I think we should update the examples as well, or? https://github.com/kubermatic/machine-controller/blob/master/examples/kubevirt-machinedeployment.yaml

**Pull request merged**
