### PR TITLE
Fix E2E tests for VMware Cloud Director

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Fix E2E tests for VMware Cloud Director.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind failing-test

**Special notes for your reviewer**:
We would like to use the latest available image against main branch for OSM. We use image caching on our CI cluster which also caches the images with `latest` tag. This results in the actual latest image not being pulled and instead we end up using whatever is there in the cache.

To fix this issue, we determine the commit SHA for the last commit on main and then consume the image against it.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
> error: unable to read URL "https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml", server reported 401 Unauthorized, status code=401

Flake
/retest

**Review by Waseem826 — APPROVED** [review]

**Pull request merged**
