### PR TITLE
Allow passing arbitrary data onto userdata plugin

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

This PR changes the userdata manager to pass the whole env down to userdata plugins, allowing to pass down arbitrary values from the top-level env.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```release-note
none
```

### CODE REVIEW

**Comment by thz** [comment]
/lgtm
/approve
/hold
(Just hold-cancel for ignoring the minor cosmetic nit.)

**Comment by alvaroaleman** [comment]
@thz updated

**Pull request merged**
