### PR TITLE
Flatcar: explicitly stop masked units on first boot

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
When we are using `ignition` for provisioning on flatcar nodes we conditionally mask the following services:
- update-engine.service
- locksmithd.service

Although just masking them isn't sufficient since that won't "stop" the services from running on the first boot.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

This is a follow up for https://github.com/kubermatic/machine-controller/pull/1219 that fixes this issue when we are using `ignition` as provisioning utility.

The new service is intentionally named just `setup` since I wanted the name to be generic.

**Optional Release Note**:

```release-note
Flatcar: explicitly stop masked units on the first boot when `ignition` is used for provisioning
```

### CODE REVIEW

**Comment by mlavacca** [comment]
@ahmedwaleedmalik is this one still WIP or Ready for review?

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik is this one still WIP or Ready for review?

It's ready for review now. I mistakenly asked for a review before updating the fixtures.

**Review by mlavacca — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
