### PR TITLE
[release/v1.45] Improvements for Anexia

### PR DESCRIPTION
**Pull request by LittleFox94**
**What this PR does / why we need it**:

This PR backports a number of improvements in our provider to the v1.45 branch. We'd like to have this backported to this version, as this is the version used by the current KKP version.

Includes the following PRs:
* #1175 
* #1288 
* #1331 
* #1402
* #1410 - this one is not merged or approved yet

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
* Anexia Provider is more resilient now and supports reattaching to ongoing provisionings after an error
* Anexia: change HTTP client timeout from 30s to 120s
* Allow configuring the disk performance type for provider Anexia
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by LittleFox94** [comment]
Using this branch works fine for us, except we run into the issue fixed by this commit:  
https://github.com/kubermatic/machine-controller/pull/1351/commits/22ddaa7d5bf6afaa376f55442be715832da1c57f

any chance to have that one commit backported as well?

**Comment by LittleFox94** [comment]
Before merging and releasing this, we need an accompanying change in kubermatic to allow the diskSize attribute to not exist.

Trying to interact with a machine deployment that has the new `[]disks` attribute and no `diskSize` attribute via kubermatic API, makes it return a 500:
`{"error":{"code":500,"message":"json: error calling MarshalJSON for type *v1.AnexiaNodeSpec: missing or invalid required parameter(s): diskSize"}}`

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
