### PR TITLE
Adding fixes for examples with deprecated and changed flags

### PR DESCRIPTION
**Pull request by frenchtoasters**
**What this PR does / why we need it**: This updates the `examples/machine-controller.yaml` to work with the latest changes.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind regression

**Special notes for your reviewer**: There might be other options that would be nice to have these are just want I had to change to get the deployments up and working. 

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note

```

**Documentation**:

```documentation

```

### CODE REVIEW

**Comment by embik** [comment]
Hi @frenchtoasters, thank you for your contribution.

I'm trying to understand the motivation behind this PR. Can you specify what exactly is fixed by it? Updating `--use-osm` to `--use-external-bootstrap` makes sense to me (thank you for doing this; I overlooked that), but the PR also removes the logging flags introduced in #1606 (why?) and adds the certificate flag defaults as of #1644, so these changes and their motivation aren't fully clear to me.

**Comment by frenchtoasters** [comment]
> Hi @frenchtoasters, thank you for your contribution.
> 
> Can you please specify what exactly is fixed by this PR, maybe by improving the description a bit? Updating `--use-osm` to `--use-external-bootstrap` makes sense to me (thank you for doing this; I overlooked that), but the PR also removes the logging flags introduced in #1606 (why?) and adds the certificate flag defaults as of #1644, so these changes and their motivation aren't fully clear to me.

Hey @embik the logging flags were removed because using the latest example from scratch those flags did not seem to work. I did see there were some other logging flags but I’m not that familiar with the project so wasn’t sure what a 1 to 1 replacement would be. 
For the cert flags they needed to be changed because the secret that was created by default did not have the .pem file for the certs and to get the webhook pod up and running I had to add those.

**Comment by embik** [comment]
Sorry for the late reply. I will check out your findings because this kind of confuses me, thanks for the additional details.

**Comment by frenchtoasters** [comment]
Here are the errors that im seeing with the log flags

```
> k logs -n kube-system machine-controller-5dc6b8769d-bsx7c                                                                                 
flag provided but not defined: -log-debug

> k logs -n kube-system machine-controller-webhook-74754f547c-d9zhd
flag provided but not defined: -log-debug

> k logs -n kube-system machine-controller-8584b8f775-xm6bg 
flag provided but not defined: -log-format

> k logs -n kube-system machine-controller-webhook-75d7bb7fdb-gl6fb 
flag provided but not defined: -log-format
```

Then here is the logs for the webhook cert using the defaults just removing the bad log flags:

```
> k logs -n kube-system machine-controller-webhook-8676b8b5b9-gswzt 
W0613 19:50:10.071869       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This m
ight not work.
I0613 19:50:10.086980       1 plugin.go:95] looking for plugin "machine-controller-userdata-amzn2"
I0613 19:50:10.087059       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-amzn2'
I0613 19:50:10.087105       1 plugin.go:95] looking for plugin "machine-controller-userdata-centos"
I0613 19:50:10.087144       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-centos'
I0613 19:50:10.087183       1 plugin.go:95] looking for plugin "machine-controller-userdata-flatcar"
I0613 19:50:10.087219       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-flatcar'
I0613 19:50:10.087253       1 plugin.go:95] looking for plugin "machine-controller-userdata-rhel"
I0613 19:50:10.087288       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-rhel'
I0613 19:50:10.087323       1 plugin.go:95] looking for plugin "machine-controller-userdata-ubuntu"
I0613 19:50:10.087373       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-ubuntu'
I0613 19:50:10.087396       1 plugin.go:95] looking for plugin "machine-controller-userdata-rockylinux"
I0613 19:50:10.087455       1 plugin.go:136] found '/usr/local/bin/machine-controller-userdata-rockylinux'
F0613 19:50:10.087604       1 main.go:134] Failed to start server: open /tmp/cert/cert.pem: no such file or directory
```

**Comment by embik** [comment]
Hi @frenchtoasters, as an update, we just released v1.57.0. This updated the `latest` tag and means the examples should all work now and this PR is no longer needed. We are also tracking a split between user-facing and internal manifests in #1663. Would you agree we can close the PR?

**Comment by embik** [comment]
I will close this PR as we didn't get a response and the issue this PR tried to solve should no longer be present.

**Pull request closed without merging**
