### PR TITLE
Enable OperatingSystemManager in E2E tests

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Enable OperatingSystemManager in E2E tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
* Operating System Manager is enabled by default and it's responsible for creating and managing the required configurations for worker nodes. 
* [ACTION REQUIRED] Existing worker machines will not be migrated to use OSM automatically. Users need to update the `MachineDeployments` manually or simply delete the machines to ensure that the machines are consuming configurations created by OSM.
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
/test pull-machine-controller-e2e-vmware-cloud-director 

Credentials were stale

**Comment by ahmedwaleedmalik** [comment]
/hold
We need a new release for OSM to move forward with this PR.

**Comment by ahmedwaleedmalik** [comment]
/test all
/test pull-machine-controller-e2e-vmware-cloud-director
/test pull-machine-controller-e2e-alibaba
/test pull-machine-controller-e2e-equinix-metal
/test pull-machine-controller-e2e-azure-redhat-satellite

😵‍💫

**Comment by ahmedwaleedmalik** [comment]
/test all
/test pull-machine-controller-e2e-vmware-cloud-director
/test pull-machine-controller-e2e-alibaba
/test pull-machine-controller-e2e-equinix-metal
/test pull-machine-controller-e2e-azure-redhat-satellite

😉

**Review by moadqassem — APPROVED** [review]
Love it! 
/approve
/lgtm

**Comment by ahmedwaleedmalik** [comment]
/unhold

🎏

**Pull request merged**
