### PR TITLE
Flatcar stop disabled units

### PR DESCRIPTION
**Pull request by HaveFun83**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

When `FlatcarConfig.DisableUpdateEngine` is set to true the update-engine.service is not stopped on new provisioned machines, which lead to an unwanted auto-updates to the latest flatcar version with a followed reboot. 
Only after this first reboot the service is then disabled.
The stop command stop the systemd service instantly to suppress the first auto-update on new provisioned machines.

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
fix disable auto-update when FlatcarConfig.DisableUpdateEngine is set to true
```

### CODE REVIEW

**Comment by HaveFun83** [comment]
@ahmedwaleedmalik is there a documented way to edit the flatcar/testdata/ignition* files? The stop command is missing here. I can edit but then the files are json beautified.

**Comment by moadqassem** [comment]
> @ahmedwaleedmalik @moadqassem is there a documented way to edit the flatcar/testdata/ignition* files? The stop command is missing here. I can edit but then the files are json beautified.

@HaveFun83 Unfortunately not, but what you can do is, go to the ignition test and add the field `DisableUpdateEngine` here https://github.com/kubermatic/machine-controller/blob/master/pkg/userdata/flatcar/provider_test.go#L150. However, I am looking at the tests that are failing and I have the impression that, the tests are failing because of this newly introduced field. Are you sure that the field `command` is a valid ignition v1.20.1 field ?

**Comment by ahmedwaleedmalik** [comment]
@HaveFun83 this doesn't seem to be a valid field for the ignition config https://github.com/coreos/ignition/blob/spec2x/config/v2_2/types/schema.go#L221

**Comment by HaveFun83** [comment]
i removed the unsupported `command: stop` from the userDataIgnitionTemplate.

**Comment by ahmedwaleedmalik** [comment]
This PR only provides a partial solution i.e. it only fixes it for `cloud-init` and not `ignition` provisioning. We'll go ahead with this and then work on fixing this for ignition later.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
