### PR TITLE
Anexia Provider: allow configuration of multiple disks

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
This PR enables configuration of multiple disks for the Anexia provider.

**What type of PR is this?**
/kind feature

**Special notes for your reviewer**:
Backporting to 1.54 and 1.56 caused merge conflicts locally. So I'll create two additional PRs as soon as this is accepted.

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: allow configuration of multiple disks
```

**Documentation**:

```documentation
examples/anexia-machinedeployment.yaml
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/hold since we are in the middle of a code freeze I'm not sure if we can move ahead with this change before the new release. But I'll leave that decision up to the @kubermatic/sig-release-managers.

**Comment by embik** [comment]
Hey @marioreggiori, we are going to cut the next machine-controller release very soon and after branching off our release branch, we'll be able to pick this PR up to go into `main`.

**Pull request merged**
