### PR TITLE
AWS: Increase HttpPutResponseHopLimit to 3 for EC2 instances

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
The latest Ubuntu 22.04 images have IMDSv2 enabled as a default. By default, the limit of hops of PUT requests to metadata service is 2. The instance metadata service is not reachable from the container network in case if further hops are required.

We came across this issue while working with Cilium as CNI. The issue has been documented [here](https://github.com/cilium/cilium/issues/25232).

Although, the issue mentions a workaround to make it work with Cilium. Fixing it just for a single component is not ideal since a tool like `machine-controller` shouldn't judge how the underlying network or programs hosted on the machines provisioned by it are configured. Hence, we went with a more generic fix for this, i.e. to set the [HTTP PUT response hop limit](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceMetadataOptionsRequest.html#:~:text=HttpPutResponseHopLimit) to 3. This ensures a much wider compatibility.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind bug

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
AWS: Increase HttpPutResponseHopLimit to 3 for EC2 instances
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
/hold
Looks like we don't run AWS tests by default in MC, let me quickly check this

**Comment by alexinfoblox** [comment]
@ahmedwaleedmalik, hello
We encountered the same issue when retrieving the session token from the instance metadata. We are also using Cilium as the cluster CNI (no issues were observed with Flannel).

Therefore, we are also considering increasing the hop limit to 3. What potential drawbacks or concerns should we be aware of when increasing it?"

**Pull request merged**
