### PR TITLE
Bump Go version to 1.22.4

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:
This PR is to update Go version to 1.22.4.
Related to https://github.com/kubermatic/infra/pull/2707

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Update Go version to 1.22.4
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]
We have the same issue with this PR as well.

The following files also need to be updated:
- https://github.com/kubermatic/machine-controller/blob/main/Dockerfile#L15
- https://github.com/kubermatic/machine-controller/blob/main/Makefile#L17
- https://github.com/kubermatic/machine-controller/blob/main/hack/update-fixtures.sh#L22

**Review by embik — APPROVED** [review]
/approve

**Comment by ahmedwaleedmalik** [comment]
/hold

To make way for https://github.com/kubermatic/machine-controller/pull/1802

**Pull request merged**
