### PR TITLE
Aws optional public ip

### PR DESCRIPTION
**Pull request by mrIncompetent**
**What this PR does / why we need it**:
This PR makes the public IP assignment for AWS instances optional.

**Special notes for your reviewer**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mrIncompetent** [comment]
@alvaroaleman 
I had to remove the `assignPublicIP` from the tests again as this only works in subnets which use a NAT gateway.
I've manually tested this in a AWS tenant which had this, but was not able to create an working environment in our AWS tenant :(

**Comment by alvaroaleman** [comment]
> I had to remove the assignPublicIP from the tests again as this only works in subnets which use a NAT gateway.

Can you add that info to the example?

**Comment by kron4eg** [comment]
wait a sec, isn't it enough to just drop instance into "private" subnet and that's end of the story?

**Comment by mrIncompetent** [comment]
> wait a sec, isn't it enough to just drop instance into "private" subnet and that's end of the story?

Also requires a NAT gateway to have internet access. I haven't figured out to correctly configure it & did not wanted to spent much time on it.

**Comment by kron4eg** [comment]
we have example config in terraform which can be translated to go calls directly :) https://github.com/kubermatic/kubeone/blob/master/examples/terraform/aws-private/main.tf

**Comment by alvaroaleman** [comment]
> wait a sec, isn't it enough to just drop instance into "private" subnet and that's end of the story?

Thats an ortohonal thing to do or not? Instances can always have a public IP associated, it just wont work in some cases.

**Comment by alvaroaleman** [comment]
/lgtm
/hold

In case you want to continue discussing pre-merge

**Pull request merged**
