### PR TITLE
update cri defaulting

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Since k8s versions below 1.24 supports docker, there is no need to default cri to containerd when users decides to use docker
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
None
```

### CODE REVIEW

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve
/lgtm

**Comment by xrstf** [comment]
/lgtm cancel

to prevent retests

**Pull request merged**
