### PR TITLE
typo in vmSize for azure provider.go

### PR DESCRIPTION
**Pull request by ams0**
**What this PR does / why we need it**:

Fixes a typo in the azure provider

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```release-note
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Hey @ams0 thanks for your pull! Can you add the `signed-off-by` as described in the second comment by the bot so we can get this merged?

**Comment by alvaroaleman** [comment]
Please remove the unsigned merge commit from this pull via a `git reset HEAD~1 && git push origin - - force-with-lease` and then we are good to go :)

**Comment by ams0** [comment]
Thanks @alvaroaleman , just did it. Great project btw!

**Pull request merged**
