### PR TITLE
Update Go dependencies and DCO

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
This PR does the following:
- Bump GO Dependencies to the latest version.
- Update DCO

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Review by mfranczy — APPROVED** [review]
/approve
/lgtm

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-vsphere

last override in this repo.

**Pull request merged**
