### PR TITLE
adding kubevirt-operator-0.26.4.yaml

### PR DESCRIPTION
**Pull request by moadqassem**
**What this PR does / why we need it**:
Upgrading kubevirt to v0.26.4
**Which issue(s) this PR fixes**
Fixes kubermatic/machine-controller#727

**Optional Release Note**:

```release-note
None
```

### CODE REVIEW

**Comment by kron4eg** [comment]
I think it’s safe to override failing job since it’s not connected to the change.

**Comment by moadqassem** [comment]
@kron4eg Yeah this PR has nothing to do with the change, however, I have a feeling why coreos is failing and I think that's related to the ignition feature gate in the kubevirt cluster

**Pull request closed without merging**
