### PR TITLE
Use official Nutanix SDK for Go

### LINKED ISSUE #1419: Move to `github.com/nutanix-cloud-native/prism-go-client` for Nutanix client
https://github.com/nutanix-cloud-native/prism-go-client now supports `context.Context` in calls, so we should move from my extracted client code to this official upstream library.

## Acceptance Criteria

- Dependency on `github.com/embik/nutanix-client-go` is replaced with `github.com/nutanix-cloud-native/prism-go-client`.

### PR DESCRIPTION
**Pull request by embik**
**What this PR does / why we need it**:

This moves from a self-maintained version of the Nutanix SDK to the official source maintained by Nutanix.

**Which issue(s) this PR fixes**:

Fixes #1419

**What type of PR is this?**
/kind cleanup

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
A dependency injected by the Nutanix SDK is down right now, thus builds are failing. See https://github.com/keploy/keploy/issues/212 for upstream issue I've opened.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Pull request merged**
