### PR TITLE
Update TLS Cipher Suites config for kubelet and restrict the allowed values

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Kubernetes, by default, supports a vast number of TLS cipher suites including some with known security concerns which weakens the protection provided by them.

Hence, we are limiting the allowed cipher suites for `kubelet` to the recommended and most secure algorithms:

TLS 1.3 cipher suites:
```text
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
```

TLS 1.0 - 1.2 cipher suites:
```text
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubermatic/edgematic/issues/65

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Review by moadqassem — COMMENTED** [review]
/hold

vSphere tests will keep failing, due to malfunctioning in the image that we use. Please retry to merge this after this PR is merged: https://github.com/kubermatic/machine-controller/pull/1086

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
