### PR TITLE
label machines metric with kubelet version

### PR DESCRIPTION
**Pull request by multi-io**
**What this PR does / why we need it**:

This adds a `kubelet_version` label to the `machine_controller_machines` Prometheus metric, making it more useful for getting a quick overview of installed machine versions in running clusters.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Hey @multi-io,

thanks for the pull!

Generally speaking this looks fine, but please be aware that we currently have an open PR #270 which will change the way we collect machine-controller metrics to be mostly stateless and we want that to go in first before we do further changes in the metrics, hence this will have to wait a moment and most likely needs a rebase then.

**Comment by multi-io** [comment]
I see @alvaroaleman . Thanks for the update. I'll wait for #270, then. :)

**Comment by mrIncompetent** [comment]
@multi-io https://github.com/kubermatic/machine-controller/pull/270 has been merged!

**Comment by multi-io** [comment]
Great, thanks. I'll rebase tonight when I have time.

**Comment by multi-io** [comment]
"Tonight" became next week, but here it is.

**Pull request merged**
