### PR TITLE
improves the way we clear node ref on the machine

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**: improves the way we clear node ref on the machine

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@alvaroaleman I have change the code as we discussed via slack.
@alvaroaleman I hope you don't mind I did it :)

**Comment by alvaroaleman** [comment]
No I definitely don't mind, thanks for doing this, works like a charm!

**Comment by p0lyn0mial** [comment]
@mrIncompetent since you are the code owner please tag the pull, otherwise i cannot merge it.

**Comment by p0lyn0mial** [comment]
just `Gopkg.lock` update

**Pull request merged**
