### PR TITLE
update to Go 1.17.1

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates all jobs to use Go 1.17.1 and bumps a few other dependencies as well.

**Optional Release Note**:
```release-note
Updated to Go 1.17.1
```

### CODE REVIEW

**Comment by kron4eg** [comment]
one does not simply upgrade golangci-lint ;)

**Comment by xrstf** [comment]
lol our boilerplate tool can't handle the new go build constraints

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
