### PR TITLE
dynamic-config-dir is set only for kubernetes < 1.23

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Optional Release Note**:

```release-note
dynamic-config-dir is set only for kubernetes < 1.23
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-azure
/override pull-machine-controller-e2e-vsphere

As requested by @xmudrii

**Review by xmudrii — APPROVED** [review]
The Azure job is failing because the CentOS image is missing. We'll fix this in a follow-up. The vSphere job is failing because there seems to be some problem with the VM template that we'll investigate.

/hold cancel

**Pull request merged**
