### PR TITLE
Upgrade to Go 1.20.2

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
**What this PR does / why we need it**:
Upgrade to Go 1.20.2.

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Machine Controller is now built using Go 1.20.2
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@ahmedwaleedmalik let's split Go update and massive dependencies update

**Comment by ahmedwaleedmalik** [comment]
> @ahmedwaleedmalik let's split Go update and massive dependencies update

Okay, will update the PR 👍

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-vmware-cloud-director

temporarily unavailable

**Review by xmudrii — APPROVED** [review]

**Pull request closed without merging**
