### PR TITLE
Add release note section to PR template

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Because we want release notes

### CODE REVIEW

**Comment by mrIncompetent** [comment]
Currently i've been writing them manual, is there any tool, which parses the PR's and creates release notes from the PR descriptions?

**Comment by alvaroaleman** [comment]
Not that I know of, but I didn't search either. I created this PR because @scheeles wanted to have the release notes in the PR descriptions and I thought it is better to start collecting that data asap.

**Comment by mrIncompetent** [comment]
Its more work to go trough each closed PR to collect the notes, than opening the diff-page in Github and taking/rewording the commit messages.

So i would rather have something which makes the task easier.

**Comment by alvaroaleman** [comment]
Closing for now as we do not have an auomated way to collect release notes from PRs yet.

**Comment by scheeles** [comment]
I think there is a tool. Let me check with Ihor from CNCF

**Comment by scheeles** [comment]
Here is the tool from k8s https://github.com/kubernetes/release/blob/master/relnotes

And this is the repo fro k8s release https://github.com/kubernetes/release

**Comment by mrIncompetent** [comment]
The project has not enough traction so it does not make sense to automatically scrape the release note section. The manual aproach does not hurt.

**Pull request closed without merging**
