### PR TITLE
Fix cleanup for machines on azure

### LINKED ISSUE #1285: Cluster deletion stucks when there is a no node due to quota limit
### What happened?
- Created a user cluster on Azure with public IP Enabled
- Azure public IP quota got reached
- Cluster has a machine but no nodes due to no network interface created and which was due to quota limit. 
```
 Warning  ReconcilingError  2m14s (x20 over 14m)  machine_controller  failed to create machine at cloudprovider, due to failed to create public IP: failed to create public IP address: network.PublicIPAddressesClient#CreateOrUpdate: │
│  Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPCountLimitReached" Message="Cannot create more than 25 public IP addresses for this subscription in this region." Details=[]
```
- Try deleting a cluster
- The cluster was not deleted even after a long wait
- Error in controller Manager
```
controller-manager {"level":"error","time":"2022-03-16T13:59:47.590Z","logger":"kubermatic_kubernetes_controller","caller":"kubernetes/cluster_controller.go:259","msg":"Reconciling failed","worker-name":"","request":"/8786dh5t6v","cluster":"8786dh5t6v","error":"Cluster.kubermatic.k8s.io \"8786dh5t6v\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"kubermatic.io/cleanup-usersshkeys-cluster-ids\"}","errorCauses":[{"error":"Cluster.kubermatic.k8s.io \"8786dh5t6v\" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{\"kubermatic.io/cleanup-usersshkeys-cluster-ids\"}"}]}
```
### What should happen?
Cluster deletion should work irrespective of the status of a nodes.
### How to reproduce?
Follow steps mentioned in _What happened_ section with public IP quota limit.
### Environment
- KKP Version: 2.18.7
- Shared or separate master/seed clusters?: separate
- Master/seed cluster provider: ANY (in our case, it was Azure as master and vsphere as seed)

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:
Fix cleanup for machines on azure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
Fixes #1285

**Special notes for your reviewer**:
I don't think we need a release note for updating `github.com/Azure/azure-sdk-for-go` to v64.1.0 or do we?

**Optional Release Note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by embik** [comment]
This makes sense to me personally, but I wonder why it was done differently in the first place. How does it fix the bug in question by the way?

**Comment by ahmedwaleedmalik** [comment]
> How does it fix the bug in question by the way?

Basically, you get left with a finalizer for `public IP` on the machine but it's never removed. It tries to clean up and returns when the instance is not found https://github.com/kubermatic/machine-controller/blob/azure-cleanup/pkg/cloudprovider/provider/azure/provider.go#L739

Cluster cleanup fails as a result.

I have ideas for further improvements in this particular case. But for now this PR should be enough for fixing the customer issue.

**Comment by ahmedwaleedmalik** [comment]
> https://github.com/kubermatic/machine-controller/pull/288#issuecomment-408425491 this is where the decision was made to add the finalizers beforehand. Essentially it's done so machine-controller does not forget to clean up a resource in case adding the finalizer fails. I can see where that is coming from.

We `delete` the resource BEFORE removing or checking for the finalizer. So I don't think that statement is valid anymore.

**Review by embik — APPROVED** [review]
/approve

**Pull request merged**
