### PR TITLE
Update Kubernetes dependencies

### PR DESCRIPTION
**Pull request by xrstf**
**What this PR does / why we need it**:
This updates k8s.io deps from 0.16.4 to 0.19.4 and controller-runtime from 0.4 to 0.6.4.

**Optional Release Note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
@xrstf Rebase is needed.

**Comment by moadqassem** [comment]
@xrstf Once you have the required tests green, please run all the prow jobs(tests)

**Comment by xrstf** [comment]
Errr...thanks for explaining how Prow works, guys... :-D

**Review by kron4eg — APPROVED** [review]

**Pull request merged**
