### PR TITLE
Change baseurl to vault.centos.org for CentOS 8

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

Change baseurl to vault.centos.org for CentOS 8.

**Optional Release Note**:
```release-note
Change baseurl to vault.centos.org for CentOS 8
```

/assign @kron4eg @moadqassem

### CODE REVIEW

**Review by kron4eg — APPROVED** [review]

**Review by moadqassem — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
