### PR TITLE
Anexia Provider: add support for named VM templates

### PR DESCRIPTION
**Pull request by marioreggiori**
**What this PR does / why we need it**:
This PR adds support for named templates. Template IDs may break over time when a new build is released. With named templates the latest build can be selected without specifying the Template ID.

**What type of PR is this?**
/kind feature
/kind documentation
/kind api-change

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
Anexia Provider: Optionally configure "named templates" instead of (less stable) "template identifiers".
```

**Documentation**:

```documentation
https://github.com/kubermatic/machine-controller/blob/main/docs/anexia.md
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
> pull-machine-controller-e2e-anexia 

@marioreggiori seems like `flatcar on v1.26.0` is not working maybe.

**Comment by marioreggiori** [comment]
> > pull-machine-controller-e2e-anexia
> 
> @marioreggiori seems like `flatcar on v1.26.0` is not working maybe.

The installed containerd version on our Flatcar nodes is `v1.5.9`, but [Kubernetes v1.26 requires at least `v1.6.0`](https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/#cri-v1alpha2-removed). Not sure yet if this is the only incompatibility.. but the failing `Kubernetes v1.26` tests should be unrelated to the changes of this PR.

**Review by ahmedwaleedmalik — APPROVED** [review]
/approve

**Comment by LittleFox94** [comment]
> My advise would be to get the flatcar issue fixed as well, in a separate PR, otherwise we'd end up with broken tests for Anexia.

fixing our template build automation, so we are going to have recent flatcar images in the near future

Your CI probably still uses a hard-coded template ID though, maybe change that to the named template soon :)

**Pull request merged**
