### PR TITLE
Fix version of k8s.io/client-go in go.mod to v0.26.4

### PR DESCRIPTION
**Pull request by kron4eg**
**What this PR does / why we need it**:
There are no (anymore) upstream dependencies that require this "broken" version which forced us to `replace` in go.mod

```
$ go mod graph | grep " k8s.io/client-go@"
github.com/kubermatic/machine-controller k8s.io/client-go@v12.0.0+incompatible
github.com/nutanix-cloud-native/prism-go-client@v0.3.4 k8s.io/client-go@v0.24.2
github.com/tinkerbell/tink@v0.8.0 k8s.io/client-go@v0.23.0
k8s.io/apiextensions-apiserver@v0.26.4 k8s.io/client-go@v0.26.4
k8s.io/cloud-provider@v0.26.4 k8s.io/client-go@v0.26.4
k8s.io/component-base@v0.26.4 k8s.io/client-go@v0.26.4
sigs.k8s.io/controller-runtime@v0.14.6 k8s.io/client-go@v0.26.1
```

Removing `replace` directive from go.mod fixes the same issues in downstream dependencies like K1 and KKP. Effectively enabling kubeone to be `go install`-able.

**What type of PR is this?**
/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by ahmedwaleedmalik** [comment]
@kron4eg I think we don't need the release note here since this doesn't really change anything for the user. WDYT?

**Comment by kron4eg** [comment]
error: the server doesn't have a resource type "machinedeployment" :shrug: 

/retest

**Pull request merged**
