### PR TITLE
Remove cloud-init flag from the Anexia provider

### PR DESCRIPTION
**Pull request by eqrx**
**What this PR does / why we need it**:
I was asked to remove this flag since internal changes in Anexia now make this flag counter productive.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged)*:
None

**Special notes for your reviewer**:
None

**Optional Release Note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mfranczy** [comment]
Seems Anexia is constantly failing, let's in the VM log what's going on there.

**Comment by moadqassem** [comment]
@eqrx It looks like Anexia service is not stable: 
```shell
received error from api: {Code:503 Message:Service Unavailable: Something went wrong. Please contact support. Validation:map[]} occurred
```

I would suggest you create those machines via the api first and then try again :)

**Comment by eqrx** [comment]
@moadqassem any idea why the hetzner tests fail?

**Comment by moadqassem** [comment]
> @moadqassem any idea why the hetzner tests fail?

I will take a look

**Comment by moadqassem** [comment]
@eqrx It looks like there are some issues for Hetzner regarding terraform scripts that were updated. Please rebase against the master and hopefully this PR will pass :)

**Comment by eqrx** [comment]
@moadqassem still broken

**Comment by eqrx** [comment]
@xmudrii @kron4eg could you guys help here?

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xrstf** [comment]
/override pull-machine-controller-e2e-hetzner

Overriding because Hetzner's API is so slow sometimes (requests can range anywhere from 0.1 to over 60 seconds!) that the kube-apiserver simply gives up waiting for the MC webhook to validate MachineDeployments, leading to test failures.

**Pull request merged**
