### PR TITLE
Use downstream clientset for cluster-api

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold

kubernetes-sigs/cluster-api#589 has merged, with updates the typed client, lister and informer, adds a fake client and adds a check to CI to ensure the generated client is up to date. I think that makes this PR superfluous.

**Comment by mrIncompetent** [comment]
> kubernetes-sigs/cluster-api#589 has merged, with updates the typed client, lister and informer, adds a fake client and adds a check to CI to ensure the generated client is up to date. I think that makes this PR superfluous.

Any chance so far to check this?

**Comment by alvaroaleman** [comment]
Closing in favor of #415 , we don't need this now that upstream verifies the generation of a typed client

**Pull request closed without merging**
