### PR TITLE
Upgrade to flannel v0.19.2 for E2E tests

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Signed-off-by: Waleed Malik <ahmedwaleedmalik@gmail.com>

**What this PR does / why we need it**:

The image from https://raw.githubusercontent.com/flannel-io/flannel/v0.18.0/Documentation/kube-flannel.yml seems broken.

```
Failed to pull image "rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0": failed to read expected number of bytes: unexpected EOF
```

**Which issue(s) this PR fixes**:

Fixes #

**What type of PR is this?**

/kind chore

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change? Then add your Release Note here**:

```release-note
NONE
```

**Documentation**:

```documentation
NONE
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@ahmedwaleedmalik oh no, you will have to `commit --amend` and `push --force` to remove the `.DS_Store` file

**Comment by ahmedwaleedmalik** [comment]
@kron4eg idk how it got in here, updated 👍

**Pull request merged**
